---
# Copyright (C) SchedMD LLC.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Include OS-specific variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution | lower }}.yml"
        - "{{ ansible_os_family | lower }}.yml"
      paths:
        - "vars"

- name: Install Python
  ansible.builtin.shell: |
    #!/bin/bash

    INSTALL_DIR="/slurm/python"
    mkdir -p "${INSTALL_DIR}"
    cd "${INSTALL_DIR}" || exit 1

    curl -LO "https://www.python.org/ftp/python/3.13.1/Python-3.13.1.tgz"
    tar -xzf "Python-3.13.1.tgz" -C "${INSTALL_DIR}"
    cd "$INSTALL_DIR/Python-3.13.1" || exit 1
    ./configure --prefix="/slurm/python"
    make altinstall
    cd "${INSTALL_DIR}" || exit 1
    rm -rf Python-3.13.1*
  args:
    executable: /bin/bash
    creates: /slurm/python/bin/python3.13

- name: Create virtualenv for tool
  ansible.builtin.pip:
    name: pip==25.0
    virtualenv: "/slurm/python/venv"
    virtualenv_command: /slurm/python/bin/python3.13 -m venv --copies

- name: Install Packages
  package:
    name: '{{python_packages}}'
    state: present

- name: update alternatives to python38
  shell:
    cmd: alternatives --set python3 /usr/bin/python3.8
  when: python38_installed

- name: Copy Pip Requirements File
  copy:
    src: ../files/slurm-gcp-requirements.txt
    dest: /tmp/requirements.txt
  register: requirements_file

- name: Install Pip Packages
  pip:
    requirements: /tmp/requirements.txt
    extra_args: --upgrade --ignore-installed {{ extra_pip_args }}
    virtualenv: "/slurm/python/venv"
    state: present
